// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7qvNFScOFM_-FrusL-2ttPBXoMMrWUXg',
    appId: '1:176269215879:web:13cfad9dc32a8c137e9022',
    messagingSenderId: '176269215879',
    projectId: 'kigalidirectory-3b859',
    authDomain: 'kigalidirectory-3b859.firebaseapp.com',
    storageBucket: 'kigalidirectory-3b859.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5hotl1EDOJyI5QuF1cOA3ro75w_vvmnY',
    appId: '1:176269215879:android:5f35cc57413efa987e9022',
    messagingSenderId: '176269215879',
    projectId: 'kigalidirectory-3b859',
    storageBucket: 'kigalidirectory-3b859.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt-2qNpCY8A20BFD_xficxWhBUXJIru8o',
    appId: '1:176269215879:ios:62659aa035abd1337e9022',
    messagingSenderId: '176269215879',
    projectId: 'kigalidirectory-3b859',
    storageBucket: 'kigalidirectory-3b859.firebasestorage.app',
    iosBundleId: 'com.example.map',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt-2qNpCY8A20BFD_xficxWhBUXJIru8o',
    appId: '1:176269215879:ios:62659aa035abd1337e9022',
    messagingSenderId: '176269215879',
    projectId: 'kigalidirectory-3b859',
    storageBucket: 'kigalidirectory-3b859.firebasestorage.app',
    iosBundleId: 'com.example.map',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7qvNFScOFM_-FrusL-2ttPBXoMMrWUXg',
    appId: '1:176269215879:web:1b5f9cdf0218141d7e9022',
    messagingSenderId: '176269215879',
    projectId: 'kigalidirectory-3b859',
    authDomain: 'kigalidirectory-3b859.firebaseapp.com',
    storageBucket: 'kigalidirectory-3b859.firebasestorage.app',
  );
}
